extern void init_rdf (void); 
extern gptr *rdf_ptr (void); 
extern void new_lins (void); 
extern int lines_left (void); 
extern void new_page (void); 
extern void new_line (void); 
extern void banner_page (void); 
extern void note (char *format, ...); 
extern void message (int *nerrs, ...); 
extern void error (char *format, ...); 
extern char *mystrdup (char *s); 
extern int get_int (char *prompt, int lo, int hi); 
extern real get_real (char *prompt, real lo, real hi); 
extern int get_sym (char *prompt, char *cset); 
extern char *get_str (char *prompt); 
extern int forstr (char *instr, int *start, int *finish, int *inc); 
extern void dump_to_moldy (float *buf, system_mt *system); 
extern void invert (real (*a)[3], real (*b)[3]);
extern void mat_vec_mul (real (*m)[3], vec_mp in_vec, vec_mp out_vec, int number);
extern void traj_con (system_mt *system, vec_mt (*prev_cofm), int n); 
extern void traj_con2 (spec_mt *species, vec_mt (*prev_cofm), vec_mt (*traj_cofm), int *sp_range); 
extern int range_in (system_mt *system, real (*range)[3]); 
extern char *comm;
